-- MySQL Script generated by MySQL Workbench
-- 08/16/20 11:39:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinesystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinesystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinesystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cinesystem` ;

-- -----------------------------------------------------
-- Table `cinesystem`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Sala` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Idioma` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Classificacao` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Categoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Legenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Legenda` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Filme` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) NULL COMMENT '',
  `duracao` INT NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  `codIdioma` INT NOT NULL COMMENT '',
  `codClassificacao` INT NOT NULL COMMENT '',
  `codCategoria` INT NOT NULL COMMENT '',
  `codLegenda` INT NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Filmes_Idiomas1_idx` (`codIdioma` ASC)  COMMENT '',
  INDEX `fk_Filmes_Classificacao1_idx` (`codClassificacao` ASC)  COMMENT '',
  INDEX `fk_Filmes_Categoria1_idx` (`codCategoria` ASC)  COMMENT '',
  INDEX `fk_Filmes_legenda1_idx` (`codLegenda` ASC)  COMMENT '',
  CONSTRAINT `fk_Filmes_Idiomas1`
    FOREIGN KEY (`codIdioma`)
    REFERENCES `cinesystem`.`Idioma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_Classificacao1`
    FOREIGN KEY (`codClassificacao`)
    REFERENCES `cinesystem`.`Classificacao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_Categoria1`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `cinesystem`.`Categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_legenda1`
    FOREIGN KEY (`codLegenda`)
    REFERENCES `cinesystem`.`Legenda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Usuario` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) NULL COMMENT '',
  `cpf` VARCHAR(11) NULL COMMENT '',
  `permissoes` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Sessao` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horario` TIME NULL COMMENT '',
  `dia` DATE NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  `codSala` INT NOT NULL COMMENT '',
  `codFilme` INT NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Sessao_Salas1_idx` (`codSala` ASC)  COMMENT '',
  INDEX `fk_Sessao_Filmes1_idx` (`codFilme` ASC)  COMMENT '',
  CONSTRAINT `fk_Sessao_Salas1`
    FOREIGN KEY (`codSala`)
    REFERENCES `cinesystem`.`Sala` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_Filmes1`
    FOREIGN KEY (`codFilme`)
    REFERENCES `cinesystem`.`Filme` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Poltrona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Poltrona` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codSala` INT NOT NULL COMMENT '',
  `fileira` VARCHAR(1) NULL COMMENT '',
  `numero` INT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Poltronas_Salas1_idx` (`codSala` ASC)  COMMENT '',
  CONSTRAINT `fk_Poltronas_Salas1`
    FOREIGN KEY (`codSala`)
    REFERENCES `cinesystem`.`Sala` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Ingresso` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codSessao` INT NOT NULL COMMENT '',
  `codPoltrona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '',
  INDEX `fk_Ingresso_Sessao1_idx` (`codSessao` ASC)  COMMENT '',
  INDEX `fk_Ingresso_Poltrona1_idx` (`codPoltrona` ASC)  COMMENT '',
  CONSTRAINT `fk_Ingresso_Sessao1`
    FOREIGN KEY (`codSessao`)
    REFERENCES `cinesystem`.`Sessao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Poltrona1`
    FOREIGN KEY (`codPoltrona`)
    REFERENCES `cinesystem`.`Poltrona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Venda` (
  `numero` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `emissao` DATE NULL COMMENT '',
  `total` DECIMAL(15,4) NULL COMMENT '',
  `cpfCliente` VARCHAR(11) NULL COMMENT '',
  `codUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`numero`)  COMMENT '',
  INDEX `fk_Venda_Usuario1_idx` (`codUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `cinesystem`.`Usuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`IngressoVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`IngressoVenda` (
  `codVenda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codIngresso` INT NOT NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  PRIMARY KEY (`codVenda`, `codIngresso`)  COMMENT '',
  INDEX `fk_Venda_has_Ingresso_Ingresso1_idx` (`codIngresso` ASC)  COMMENT '',
  INDEX `fk_Venda_has_Ingresso_Venda1_idx` (`codVenda` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_has_Ingresso_Venda1`
    FOREIGN KEY (`codVenda`)
    REFERENCES `cinesystem`.`Venda` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Ingresso_Ingresso1`
    FOREIGN KEY (`codIngresso`)
    REFERENCES `cinesystem`.`Ingresso` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cinesystem`.`Auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`auditoria` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `tabela` varchar(150) DEFAULT NULL,
  `new_codigo` int(11) DEFAULT NULL,
  `old_codigo` int(11) DEFAULT NULL,
  `new_dia` date DEFAULT NULL,
  `old_dia` date DEFAULT NULL,
  `new_valor` decimal(15,4) DEFAULT NULL,
  `old_valor` decimal(15,4) DEFAULT NULL,
  `new_idioma` varchar(50) DEFAULT NULL,
  `old_idioma` varchar(50) DEFAULT NULL,
  `new_descricao` varchar(150) DEFAULT NULL,
  `old_descricao` varchar(150) DEFAULT NULL,
  `new_nome` varchar(250) DEFAULT NULL,
  `old_nome` varchar(250) DEFAULT NULL,
  `new_codIdioma` int(11) DEFAULT NULL,
  `old_codIdioma` int(11) DEFAULT NULL,
  `new_codClassificacao` int(11) DEFAULT NULL,
  `old_codClassificacao` int(11) DEFAULT NULL,
  `new_codLegenda` int(11) DEFAULT NULL,
  `old_codLegenda` int(11) DEFAULT NULL,
  `new_codCategoria` int(11) DEFAULT NULL,
  `old_codCategoria` int(11) DEFAULT NULL,
  `new_cpf` varchar(11) DEFAULT NULL,
  `old_cpf` varchar(11) DEFAULT NULL,
  `new_permissoes` varchar(5) DEFAULT NULL,
  `old_permissoes` varchar(5) DEFAULT NULL,
  `new_horario` time DEFAULT NULL,
  `old_horario` time DEFAULT NULL,
  `new_codSala` int(11) DEFAULT NULL,
  `old_codSala` int(11) DEFAULT NULL,
  `new_codFilme` int(11) DEFAULT NULL,
  `old_codFilme` int(11) DEFAULT NULL,
  `new_fileira` varchar(1) DEFAULT NULL,
  `old_fileira` varchar(1) DEFAULT NULL,
  `new_numero` int(11) DEFAULT NULL,
  `old_numero` int(11) DEFAULT NULL,
  `new_codSessao` int(11) DEFAULT NULL,
  `old_codSessao` int(11) DEFAULT NULL,
  `new_codPoltrona` int(11) DEFAULT NULL,
  `old_codPoltrona` int(11) DEFAULT NULL,
  `new_emissao` date DEFAULT NULL,
  `old_emissao` date DEFAULT NULL,
  `new_total` decimal(15,4) DEFAULT NULL,
  `old_total` decimal(15,4) DEFAULT NULL,
  `new_cpfCliente` varchar(11) DEFAULT NULL,
  `old_cpfCliente` varchar(11) DEFAULT NULL,
  `new_codUsuario` int(11) DEFAULT NULL,
  `old_codUsuario` int(11) DEFAULT NULL,
  `new_codVenda` int(11) DEFAULT NULL,
  `old_codVenda` int(11) DEFAULT NULL,
  `new_codIngresso` int(11) DEFAULT NULL,
  `old_codIngresso` int(11) DEFAULT NULL,
  `new_duracao` int(11) DEFAULT NULL,
  `old_duracao` int(11) DEFAULT NULL,
  `acao` varchar(6) DEFAULT NULL,
  `usuario` varchar(50) DEFAULT NULL,
  `hora` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`)
)

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- TRIGGERS UTILIZADOS PARA A TABELA AUDITORIA
-- -----------------------------------------------------

--TRIGGERS DE AUDITORIA PARA A TABELA SALA:

create trigger auditoria_insert_sala after insert on sala  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SALA',new.codigo,null,null,null,null,null,null,null,new.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_sala after update on sala  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SALA',new.codigo,old.codigo,null,null,null,null,null,null,new.descricao,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_sala after delete on sala  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SALA',null,old.codigo,null,null,null,null,null,null,null,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());
 
--TRIGGERS DE AUDITORIA PARA A TABELA IDIOMA:

create trigger auditoria_insert_idioma after insert on idioma  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('IDIOMA',new.codigo,null,null,null,null,null,new.idioma,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_idioma after update on idioma
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('IDIOMA',new.codigo,old.codigo,null,null,null,null,new.idioma,old.idioma,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_idioma after delete on idioma  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('IDIOMA',null,old.codigo,null,null,null,null,null,old.idioma,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA CLASSIFICAÇÃO:

create trigger auditoria_insert_classificacao after insert on classificacao
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CLASSIFICAÇÃO',new.codigo,null,null,null,null,null,null,null,new.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_classificacao after update on classificacao  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CLASSIFICAÇÃO',new.codigo,old.codigo,null,null,null,null,null,null,new.descricao,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_classificacao after delete on classificacao 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CLASSIFICAÇÃO',null,old.codigo,null,null,null,null,null,null,null,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA CATEGORIA:

create trigger auditoria_insert_categoria after insert on categoria  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CATEGORIA',new.codigo,null,null,null,null,null,null,null,new.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_categoria after update on categoria  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CATEGORIA',new.codigo,old.codigo,null,null,null,null,null,null,new.descricao,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_categoria after delete on categoria
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('CATEGORIA',null,old.codigo,null,null,null,null,null,null,null,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA LEGENDA:

create trigger auditoria_insert_legenda after insert on legenda  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('LEGENDA',new.codigo,null,null,null,null,null,null,null,new.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_legenda after update on legenda  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('LEGENDA',new.codigo,old.codigo,null,null,null,null,null,null,new.descricao,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_legenda after delete on legenda  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('LEGENDA',null,old.codigo,null,null,null,null,null,null,null,old.descricao,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA FILME:

create trigger auditoria_insert_filme after insert on filme  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('FILME',new.codigo,null,null,null,new.valor,null,null,null,null,null,null,null,new.codIdioma,null,new.codClassificacao,null,new.codLegenda,null,new.codCategoria,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.duracao,null, 'INSERT', user(), now());

create trigger auditoria_update_filme after update on filme  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('FILME',new.codigo,old.codigo,null,null,null,null,new.valor,old.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.duracao,old.duracao, 'UPDATE', user(), now());

create trigger auditoria_delete_filme after delete on filme  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('FILME',null,old.codigo,null,null,null,old.valor,null,null,null,null,null,null,null,old.codIdioma,null,old.codClassificacao,null,old.codLegenda,null,old.codCategoria,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.duracao, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA USUÁRIO:

create trigger auditoria_insert_usuario after insert on usuario  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('USUÁRIO',new.codigo,null,null,null,null,null,null,null,null,null,new.nome,null,null,null,null,null,null,null,null,null,new.cpf,null,new.permissoes,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_usuario after update on usuario  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('USUÁRIO',new.codigo,old.codigo,null,null,null,null,null,null,null,null,new.nome,old.nome,null,null,null,null,null,null,null,null,new.cpf,old.cpf,new.permissoes,old.permissoes,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_usuario after delete on usuario  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('USUÁRIO',null,old.codigo,null,null,null,null,null,null,null,null,null,old.nome,null,null,null,null,null,null,null,null,old.cpf,null,old.permissoes,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA SESSÃO:

create trigger auditoria_insert_sessao after insert on sessao  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SESSÃO',new.codigo,null,new.dia,null,new.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.horario,null,new.codSala,null,new.codFilme,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_sessao after update on sessao 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SESSÃO',new.codigo,old.codigo,new.dia,old.dia,new.valor,old.valor,new.codSala,old.codSala,new.codFilme,old.codFilme,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.horario,old.horario,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_sessao after delete on sessao  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('SESSÃO',null,old.codigo,null,old.dia,null,old.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.horario,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA POLTRONA:

create trigger auditoria_insert_poltrona after insert on poltrona  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('POLTRONA',new.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.codSala,null,null,null,new.fileira,null,new.numero,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_poltrona after update on poltrona 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('POLTRONA',new.codigo,old.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.codSala,old.codSala,new.fileira,old.fileira,new.numero,old.numero,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_poltrona after delete on poltrona  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('POLTRONA',null,old.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.codSala,null,old.fileira,null,old.numero,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA INGRESSO:

create trigger auditoria_insert_ingresso after insert on ingresso  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSO',new.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.codSessao,null,new.codPoltrona,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_ingresso after update on ingresso 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSO',new.codigo,old.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.codSessao,old.codSessao,new.codPoltrona,old.codPoltrona,null,null,null,null,null,null,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_ingresso after delete on ingresso  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSO',null,old.codigo,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.codSessao,null,old.codPoltrona,null,null,null,null,null,null,null,null,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA VENDA:

create trigger auditoria_insert_venda after insert on venda 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('VENDA',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.numero,null,null,null,null,null,new.emissao,null,new.total,null,new.cpfCliente,null,new.codUsuario,null,null,null,null,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_venda after update on venda 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('VENDA',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.numero,old.numero,null,null,null,null,null,new.emissao,old.emissao,new.total,old.total,new.cpfCliente,old.cpfCliente,null,null,null,null,null,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_venda after delete on venda  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('VENDA',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.numero,null,null,null,null,null,old.emissao,null,old.total,null,old.cpfCliente,null,old.codUsuario,null,null,null,null,null,null, 'DELETE', user(), now());


--TRIGGERS DE AUDITORIA PARA A TABELA INGRESSOVENDA:

create trigger auditoria_insert_ingressovenda after insert on ingressovenda  
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSOVENDA',null,null,null,null,new.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,new.codVenda,null,new.codIngresso,null,null,null, 'INSERT', user(), now());

create trigger auditoria_update_ingressovenda after update on ingressovenda 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSOVENDA',null,null,null,null,new.valor,old.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,nw.codVenda,old.codVenda,new.codIngresso,old.codIngresso,null,null, 'UPDATE', user(), now());

create trigger auditoria_delete_ingressovenda after delete on ingressovenda 
	for each row  
           insert into auditoria(tabela,new_codigo,old_codigo,new_dia,old_dia,new_valor,old_valor,new_idioma,old_idioma,new_descricao,old_descricao,new_nome,old_nome,new_codIdioma,old_codIdioma,new_codClassificacao,old_codClassificacao,new_codLegenda,old_codLegenda,new_codCategoria,old_codCategoria,new_cpf,old_cpf,new_permissoes,old_permissoes,new_horario,old_horario,new_codSala,old_codSala,new_codFilme,old_codFilme,new_fileira,old_fileira,new_numero,old_numero,new_codSessao,old_codSessao,new_codPoltrona,old_codPoltrona,new_emissao,old_emissao,new_total,old_total,new_cpfCliente,old_cpfCliente,new_codUsuario,old_codUsuario,new_codVenda,old_codVenda,new_codIngresso,old_codIngresso,new_duracao,old_duracao, acao, usuario, hora)   
                     values('INGRESSOVENDA',null,null,null,null,null,old.valor,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,old.codVenda,null,old.codIngresso,null,null, 'DELETE', user(), now());


-- -----------------------------------------------------
-- VIEWS
-- -----------------------------------------------------

CREATE VIEW vw_CadastrosNovos
AS SELECT hora AS Data_Hora, usuario AS Usuario
FROM auditoria_log
WHERE acao = 'INSERT';

SELECT Data_Hora, Usuario
FROM vw_CadastrosNovos
ORDER BY Data_Hora;

DROP VIEW vw_CadastrosNovos;

CREATE VIEW vw_CadastrosAlterados
AS SELECT hora AS Data_Hora, usuario AS Usuario
FROM auditoria_log
WHERE acao = 'UPDATE';

SELECT Data_Hora, Usuario
FROM vw_CadastrosAlterados
ORDER BY Data_Hora;

CREATE VIEW vw_CadastrosExcluidos
AS SELECT hora AS Data_Hora, usuario AS Usuario
FROM auditoria_log
WHERE acao = 'DELETE';

SELECT Data_Hora, Usuario
FROM vw_CadastrosExcluidos
ORDER BY Data_Hora;

-- -----------------------------------------------------
-- STORED PROCEDURES
-- -----------------------------------------------------

CREATE PROCEDURE verValor (varFilme int)
SELECT CONCAT('O valor da sessão do filme ', nome, ' é ', valor) AS Valores
FROM filme
WHERE codigo = varFilme;

CALL verValor(4);

DROP PROCEDURE verValor;


delimiter $$									
create procedure verIdiomas(opcao integer)

begin

    if opcao = 0 then
        select * from filme where codIdioma = 1;
    else
        if opcao = 1 then
          select * from filme where codIdioma = 2;
        else
          select * from filme;
        end if;
    end if;
 end $$

delimiter ;

DROP PROCEDURE verLegendas;

CALL verIdiomas(1);

