-- MySQL Script generated by MySQL Workbench
-- 08/16/20 11:39:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinesystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinesystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinesystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cinesystem` ;

-- -----------------------------------------------------
-- Table `cinesystem`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Sala` (
  `Codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Idioma` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idioma` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Classificacao` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Categoria` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Legenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Legenda` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Filme` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) NULL COMMENT '',
  `duracao` INT NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  `codIdioma` INT NOT NULL COMMENT '',
  `codClassificacao` INT NOT NULL COMMENT '',
  `codCategoria` INT NOT NULL COMMENT '',
  `codLegenda` INT NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Filmes_Idiomas1_idx` (`codIdioma` ASC)  COMMENT '',
  INDEX `fk_Filmes_Classificacao1_idx` (`codClassificacao` ASC)  COMMENT '',
  INDEX `fk_Filmes_Categoria1_idx` (`codCategoria` ASC)  COMMENT '',
  INDEX `fk_Filmes_legenda1_idx` (`codLegenda` ASC)  COMMENT '',
  CONSTRAINT `fk_Filmes_Idiomas1`
    FOREIGN KEY (`codIdioma`)
    REFERENCES `cinesystem`.`Idioma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_Classificacao1`
    FOREIGN KEY (`codClassificacao`)
    REFERENCES `cinesystem`.`Classificacao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_Categoria1`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `cinesystem`.`Categoria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmes_legenda1`
    FOREIGN KEY (`codLegenda`)
    REFERENCES `cinesystem`.`Legenda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Usuario` (
  `Codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(250) NULL COMMENT '',
  `cpf` VARCHAR(11) NULL COMMENT '',
  `permissoes` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Sessao` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horario` TIME NULL COMMENT '',
  `dia` DATE NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  `codSala` INT NOT NULL COMMENT '',
  `codFilme` INT NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Sessao_Salas1_idx` (`codSala` ASC)  COMMENT '',
  INDEX `fk_Sessao_Filmes1_idx` (`codFilme` ASC)  COMMENT '',
  CONSTRAINT `fk_Sessao_Salas1`
    FOREIGN KEY (`codSala`)
    REFERENCES `cinesystem`.`Sala` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_Filmes1`
    FOREIGN KEY (`codFilme`)
    REFERENCES `cinesystem`.`Filme` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Poltrona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Poltrona` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codSala` INT NOT NULL COMMENT '',
  `fileira` VARCHAR(1) NULL COMMENT '',
  `numero` INT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Poltronas_Salas1_idx` (`codSala` ASC)  COMMENT '',
  CONSTRAINT `fk_Poltronas_Salas1`
    FOREIGN KEY (`codSala`)
    REFERENCES `cinesystem`.`Sala` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Ingresso` (
  `Codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codSessao` INT NOT NULL COMMENT '',
  `codPoltrona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Codigo`)  COMMENT '',
  INDEX `fk_Ingresso_Sessao1_idx` (`codSessao` ASC)  COMMENT '',
  INDEX `fk_Ingresso_Poltrona1_idx` (`codPoltrona` ASC)  COMMENT '',
  CONSTRAINT `fk_Ingresso_Sessao1`
    FOREIGN KEY (`codSessao`)
    REFERENCES `cinesystem`.`Sessao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Poltrona1`
    FOREIGN KEY (`codPoltrona`)
    REFERENCES `cinesystem`.`Poltrona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`Venda` (
  `numero` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `emissao` DATE NULL COMMENT '',
  `total` DECIMAL(15,4) NULL COMMENT '',
  `cpfCliente` VARCHAR(11) NULL COMMENT '',
  `codUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`numero`)  COMMENT '',
  INDEX `fk_Venda_Usuario1_idx` (`codUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `cinesystem`.`Usuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinesystem`.`IngressoVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinesystem`.`IngressoVenda` (
  `codVenda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codIngresso` INT NOT NULL COMMENT '',
  `valor` DECIMAL(15,4) NULL COMMENT '',
  PRIMARY KEY (`codVenda`, `codIngresso`)  COMMENT '',
  INDEX `fk_Venda_has_Ingresso_Ingresso1_idx` (`codIngresso` ASC)  COMMENT '',
  INDEX `fk_Venda_has_Ingresso_Venda1_idx` (`codVenda` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_has_Ingresso_Venda1`
    FOREIGN KEY (`codVenda`)
    REFERENCES `cinesystem`.`Venda` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Ingresso_Ingresso1`
    FOREIGN KEY (`codIngresso`)
    REFERENCES `cinesystem`.`Ingresso` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
