/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.ConnectionFactory;
import apoio.DB_Connection;
import daos.DaoUsuario;
import entidades.Idioma;
import entidades.Usuario;
import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.apache.log4j.Logger;

public class FrmLogin extends javax.swing.JFrame {
    
    private org.apache.log4j.Logger logger = Logger.getLogger(FrmLogin.class.getName());
    LocalDateTime agora = LocalDateTime.now();

    public Usuario usuarios;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(Usuario usuario) {
        initComponents();
        usuarios = usuario;
        this.setTitle("Login");
    }

    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfdUsuario = new javax.swing.JTextField();
        pfdSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnRelatorio1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CINESYSTEM");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnExcel.setText("Exportar Tabela Completa Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnRelatorio1.setText("Gerar Relatório PDF");
        btnRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(pfdSenha)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRelatorio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(92, 92, 92)
                                .addComponent(btnEntrar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tfdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnRelatorio1))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        char[] charSenha = pfdSenha.getPassword();
        String senha = new String(charSenha);
        DaoUsuario daoUsuario = new DaoUsuario();
        daoUsuario.consulta(usuarios, tfdUsuario.getText(), senha);
        if ("A".equals(usuarios.getPermissoes()) || ("U".equals(usuarios.getPermissoes()))) {
            cineSystem.CineSystem.login(usuarios);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos");
            logger.error(agora+" ERROR: Usuário ou senha inválidos! --  Tela de Login");
            tfdUsuario.requestFocus();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        JFileChooser excelFileChooser = new JFileChooser();
        excelFileChooser.showSaveDialog(null);
        try {
            PrintWriter pw= new PrintWriter(new File("C:\\Users\\Acer\\Documents\\NetBeansProjects\\auditoria.csv"));
            StringBuilder sb=new StringBuilder();

            Connection connection=null;
            DB_Connection obj_DB_Connection=new DB_Connection();
            connection=obj_DB_Connection.getConnection();
            ResultSet rs=null;

            String query="select * from auditoria";
            PreparedStatement ps=connection.prepareStatement(query);
            rs=ps.executeQuery();

            while(rs.next()){
                sb.append(rs.getString("log_id"));
                sb.append(",");
                sb.append(rs.getString("tabela"));
                sb.append(",");
                sb.append(rs.getString("new_codigo"));
                sb.append(",");
                sb.append(rs.getString("old_codigo"));
                sb.append(",");
                sb.append(rs.getString("new_dia"));
                sb.append(",");
                sb.append(rs.getString("old_dia"));
                sb.append(",");
                sb.append(rs.getString("new_valor"));
                sb.append(",");
                sb.append(rs.getString("old_valor"));
                sb.append(",");
                sb.append(rs.getString("new_idioma"));
                sb.append(",");
                sb.append(rs.getString("old_idioma"));
                sb.append(",");
                sb.append(rs.getString("new_descricao"));
                sb.append(",");
                sb.append(rs.getString("old_descricao"));
                sb.append(",");
                sb.append(rs.getString("new_nome"));
                sb.append(",");
                sb.append(rs.getString("old_nome"));
                sb.append(",");
                sb.append(rs.getString("new_codIdioma"));
                sb.append(",");
                sb.append(rs.getString("old_codIdioma"));
                sb.append(",");
                sb.append(rs.getString("new_codClassificacao"));
                sb.append(",");
                sb.append(rs.getString("old_codClassificacao"));
                sb.append(",");
                sb.append(rs.getString("new_codLegenda"));
                sb.append(",");
                sb.append(rs.getString("old_codLegenda"));
                sb.append(",");
                sb.append(rs.getString("new_codCategoria"));
                sb.append(",");
                sb.append(rs.getString("old_codCategoria"));
                sb.append(",");
                sb.append(rs.getInt("new_cpf"));
                sb.append(",");
                sb.append(rs.getInt("old_cpf"));
                sb.append(",");
                sb.append(rs.getString("new_permissoes"));
                sb.append(",");
                sb.append(rs.getString("old_permissoes"));
                sb.append(",");
                sb.append(rs.getDate("new_horario"));
                sb.append(",");
                sb.append(rs.getDate("old_horario"));
                sb.append(",");
                sb.append(rs.getString("new_codSala"));
                sb.append(",");
                sb.append(rs.getString("old_codSala"));
                sb.append(",");
                sb.append(rs.getString("new_codFilme"));
                sb.append(",");
                sb.append(rs.getString("old_codFilme"));
                sb.append(",");
                sb.append(rs.getInt("new_fileira"));
                sb.append(",");
                sb.append(rs.getInt("old_fileira"));
                sb.append(",");
                sb.append(rs.getString("new_numero"));
                sb.append(",");
                sb.append(rs.getString("old_numero"));
                sb.append(",");
                sb.append(rs.getString("new_codSessao"));
                sb.append(",");
                sb.append(rs.getString("old_codSessao"));
                sb.append(",");
                sb.append(rs.getString("new_codPoltrona"));
                sb.append(",");
                sb.append(rs.getString("old_codPoltrona"));
                sb.append(",");
                sb.append(rs.getString("new_emissao"));
                sb.append(",");
                sb.append(rs.getString("old_emissao"));
                sb.append(",");
                sb.append(rs.getString("new_total"));
                sb.append(",");
                sb.append(rs.getString("old_total"));
                sb.append(",");
                sb.append(rs.getString("new_cpfCliente"));
                sb.append(",");
                sb.append(rs.getString("old_cpfCliente"));
                sb.append(",");
                sb.append(rs.getString("new_codUsuario"));
                sb.append(",");
                sb.append(rs.getString("old_codUsuario"));
                sb.append(",");
                sb.append(rs.getString("new_codVenda"));
                sb.append(",");
                sb.append(rs.getString("old_codVenda"));
                sb.append(",");
                sb.append(rs.getString("new_codIngresso"));
                sb.append(",");
                sb.append(rs.getString("old_codIngresso"));
                sb.append(",");
                sb.append(rs.getString("new_duracao"));
                sb.append(",");
                sb.append(rs.getString("old_duracao"));
                sb.append(",");
                sb.append(rs.getString("acao"));
                sb.append(",");
                sb.append(rs.getString("usuario"));
                sb.append(",");
                sb.append(rs.getString("hora"));
                sb.append("\r\n");
            }

            pw.write(sb.toString());
            pw.close();
            System.out.println("finished");

        } catch (Exception e) {
            logger.error(agora+" ERROR: Erro ao exportar planilha EXCEL! --  Tela de Auditoria");
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorio1ActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/Auditoria.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatorio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConnectionFactory.getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
            logger.error(agora+" ERROR: Erro ao gerar relatório!  --  Tela Principal");
        }
    }//GEN-LAST:event_btnRelatorio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnRelatorio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pfdSenha;
    private javax.swing.JTextField tfdUsuario;
    // End of variables declaration//GEN-END:variables
}
