package telas;

import apoio.ConnectionFactory;
import apoio.DB_Connection;
import daos.DaoAuditoria;
import entidades.Auditoria;
import java.io.File;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;


public class IfrAuditoria extends javax.swing.JInternalFrame {
    private org.apache.log4j.Logger logger = Logger.getLogger(FrmLogin.class.getName());
    LocalDateTime agora = LocalDateTime.now();
    
    int codigo = 0;
    String consulta = "";
    DaoAuditoria daoAuditoria = new DaoAuditoria();
    
    public IfrAuditoria() {
        initComponents();
         inicia();
    }
    
       public void popularTabela() {

        //cabeçalho da tabela
        Object[] cabecalho = new Object[5];
        cabecalho[0] = "Código";
        cabecalho[1] = "Tabela";


        cabecalho[2] = "Ação";
        cabecalho[3] = "Usuário";
        cabecalho[4] = "DataHora";

        List<Auditoria> resultado = new ArrayList();
        String sql = "FROM auditoria "
            + "ORDER BY log_id";
        tblAuditoria.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblAuditoria.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblAuditoria.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblAuditoria.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblAuditoria.getColumnModel().getColumn(4).setPreferredWidth(30);
        
        DefaultTableModel modelo = (DefaultTableModel) tblAuditoria.getModel();
        modelo.setNumRows(0);
        try {
            DaoAuditoria daoAuditoria = new DaoAuditoria();
            resultado = daoAuditoria.consultaTodos();
            for (int i = 0; i < resultado.size(); i++) {
                Auditoria auditoria = resultado.get(i);
                modelo.addRow(new Object[]{auditoria.getLog_id(), auditoria.getTabela(),auditoria.getAcao(),auditoria.getUsuario(),auditoria.getHora()});

            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }

    }
       
    public void inicia() {
        popularTabela();
        codigo = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcel = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta de Auditoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Log ID", "Tabela", "Ação", "Usuário", "Data & Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAuditoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAuditoria);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Planilha para Consulta de Auditoria:");

        btnExcel.setText("Exportar Tabela Completa Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Gerar Relatório PDF");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcel)
                        .addGap(99, 99, 99)
                        .addComponent(btnRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExcel)
                    .addComponent(btnRelatorio))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAuditoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAuditoriaMouseClicked

    }//GEN-LAST:event_tblAuditoriaMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        JFileChooser excelFileChooser = new JFileChooser();
        excelFileChooser.showSaveDialog(null);
        try {
            PrintWriter pw= new PrintWriter(new File("C:\\Users\\Acer\\Documents\\NetBeansProjects\\auditoria.csv"));
            StringBuilder sb=new StringBuilder();

            Connection connection=null;
            DB_Connection obj_DB_Connection=new DB_Connection();
            connection=obj_DB_Connection.getConnection();
            ResultSet rs=null;

            String query="select * from auditoria";
            PreparedStatement ps=connection.prepareStatement(query);
            rs=ps.executeQuery();

            while(rs.next()){
                sb.append(rs.getString("log_id"));
                sb.append(",");
                sb.append(rs.getString("tabela"));
                sb.append(",");
                sb.append(rs.getString("new_codigo"));
                sb.append(",");
                sb.append(rs.getString("old_codigo"));
                sb.append(",");
                sb.append(rs.getString("new_dia"));
                sb.append(",");
                sb.append(rs.getString("old_dia"));
                sb.append(",");
                sb.append(rs.getString("new_valor"));
                sb.append(",");
                sb.append(rs.getString("old_valor"));
                sb.append(",");
                sb.append(rs.getString("new_idioma"));
                sb.append(",");
                sb.append(rs.getString("old_idioma"));
                sb.append(",");
                sb.append(rs.getString("new_descricao"));
                sb.append(",");
                sb.append(rs.getString("old_descricao"));
                sb.append(",");
                sb.append(rs.getString("new_nome"));
                sb.append(",");
                sb.append(rs.getString("old_nome"));
                sb.append(",");
                sb.append(rs.getString("new_codIdioma"));
                sb.append(",");
                sb.append(rs.getString("old_codIdioma"));
                sb.append(",");
                sb.append(rs.getString("new_codClassificacao"));
                sb.append(",");
                sb.append(rs.getString("old_codClassificacao"));
                sb.append(",");
                sb.append(rs.getString("new_codLegenda"));
                sb.append(",");
                sb.append(rs.getString("old_codLegenda"));
                sb.append(",");
                sb.append(rs.getString("new_codCategoria"));
                sb.append(",");
                sb.append(rs.getString("old_codCategoria"));
                sb.append(",");
                sb.append(rs.getInt("new_cpf"));
                sb.append(",");
                sb.append(rs.getInt("old_cpf"));
                sb.append(",");
                sb.append(rs.getString("new_permissoes"));
                sb.append(",");
                sb.append(rs.getString("old_permissoes"));
                sb.append(",");
                sb.append(rs.getDate("new_horario"));
                sb.append(",");
                sb.append(rs.getDate("old_horario"));
                sb.append(",");
                sb.append(rs.getString("new_codSala"));
                sb.append(",");
                sb.append(rs.getString("old_codSala"));
                sb.append(",");
                sb.append(rs.getString("new_codFilme"));
                sb.append(",");
                sb.append(rs.getString("old_codFilme"));
                sb.append(",");
                sb.append(rs.getInt("new_fileira"));
                sb.append(",");
                sb.append(rs.getInt("old_fileira"));
                sb.append(",");
                sb.append(rs.getString("new_numero"));
                sb.append(",");
                sb.append(rs.getString("old_numero"));
                sb.append(",");
                sb.append(rs.getString("new_codSessao"));
                sb.append(",");
                sb.append(rs.getString("old_codSessao"));
                sb.append(",");
                sb.append(rs.getString("new_codPoltrona"));
                sb.append(",");
                sb.append(rs.getString("old_codPoltrona"));
                sb.append(",");
                sb.append(rs.getString("new_emissao"));
                sb.append(",");
                sb.append(rs.getString("old_emissao"));
                sb.append(",");
                sb.append(rs.getString("new_total"));
                sb.append(",");
                sb.append(rs.getString("old_total"));
                sb.append(",");
                sb.append(rs.getString("new_cpfCliente"));
                sb.append(",");
                sb.append(rs.getString("old_cpfCliente"));
                sb.append(",");
                sb.append(rs.getString("new_codUsuario"));
                sb.append(",");
                sb.append(rs.getString("old_codUsuario"));
                sb.append(",");
                sb.append(rs.getString("new_codVenda"));
                sb.append(",");
                sb.append(rs.getString("old_codVenda"));
                sb.append(",");
                sb.append(rs.getString("new_codIngresso"));
                sb.append(",");
                sb.append(rs.getString("old_codIngresso"));
                sb.append(",");
                sb.append(rs.getString("new_duracao"));
                sb.append(",");
                sb.append(rs.getString("old_duracao"));
                sb.append(",");
                sb.append(rs.getString("acao"));
                sb.append(",");
                sb.append(rs.getString("usuario"));
                sb.append(",");
                sb.append(rs.getString("hora"));
                sb.append("\r\n");
            }

            pw.write(sb.toString());
            pw.close();
            System.out.println("finished");

        } catch (Exception e) {
            logger.error(agora+" ERROR: Erro ao exportar planilha EXCEL! --  Tela de Auditoria");
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        try {
            // Compila o relatorio
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/Auditoria.jrxml"));

            // Mapeia campos de parametros para o relatorio, mesmo que nao existam
            Map parametros = new HashMap();

            // Executa relatorio
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConnectionFactory.getConnection());

            // Exibe resultado em video
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
            logger.error(agora+" ERROR: Erro ao gerar relatório!  --  Tela Auditoria");
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAuditoria;
    // End of variables declaration//GEN-END:variables
}
