package telas;

import daos.DaoCategoria;
import daos.DaoClassificacao;
import daos.DaoFilme;
import daos.DaoGenerico;
import daos.DaoIdioma;
import daos.DaoLegenda;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import entidades.Categoria;
import entidades.Classificacao;
import entidades.Idioma;
import entidades.Legenda;
import entidades.Filme;
import java.awt.Color;
import javax.swing.JComboBox;

/**
 *
 * @author Acer
 */
public class IfrFilme extends javax.swing.JInternalFrame {

    int codigo = 0;
    String consulta = "";
    DaoCategoria daoCategoria = new DaoCategoria();
    DaoIdioma daoIdioma = new DaoIdioma();
    DaoClassificacao daoClassificacao = new DaoClassificacao();
    DaoLegenda daoLegenda = new DaoLegenda();

    /**
     * Creates new form IfrFilme
     */
    public IfrFilme() {
        initComponents();
        inicia();
    }

    public void popularTabela() {

        // cabecalho da tabela
        Object[] cabecalho = new Object[6];
        cabecalho[0] = "Código";
        cabecalho[1] = "Nome";
        cabecalho[2] = "Duração";
        cabecalho[3] = "Valor";
        cabecalho[4] = "Idioma";
        cabecalho[5] = "Categoria";

        List<Filme> resultado = new ArrayList();
        tblFilme.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(5).setPreferredWidth(50);
        DefaultTableModel modelo = (DefaultTableModel) tblFilme.getModel();
        modelo.setNumRows(0);
        try {
            DaoFilme daoFilme = new DaoFilme();
            resultado = daoFilme.consultaTodos();
            for (int i = 0; i < resultado.size(); i++) {
                Filme filme = resultado.get(i);
                modelo.addRow(new Object[]{filme.getCodigo(), filme.getNome(), filme.getDuracao(), filme.getValor(), filme.getIdioma(), filme.getCategoria()});

            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }

        // permite seleção de apenas uma linha da tabela
        tblFilme.setSelectionMode(0);
    }

    public void inicia() {
        tfdBuscar.setText("");
        tfdNome.setText("");
        tfdDuracao.setText("");
        tfdValor.setText("");
        popularTabela();
        codigo = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdDuracao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        tfdCdIdioma = new javax.swing.JTextField();
        tfdCdLegenda = new javax.swing.JTextField();
        tfdCdClassificacao = new javax.swing.JTextField();
        tfdCdCategoria = new javax.swing.JTextField();
        tfdIdioma = new javax.swing.JTextField();
        tfdLegenda = new javax.swing.JTextField();
        tfdClassificacao = new javax.swing.JTextField();
        tfdCategoria = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilme = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Cadastro de Filmes");

        jLabel2.setText("Nome:");

        jLabel3.setText("Duração:");

        tfdDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDuracaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor:");

        jLabel5.setText("Idioma:");

        jLabel6.setText("Legenda:");

        jLabel7.setText("Categoria:");

        jLabel8.setText("Classificação:");

        lblMensagem.setText("Mensagem");

        tfdCdIdioma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdCdIdiomaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCdIdiomaFocusLost(evt);
            }
        });

        tfdCdLegenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdCdLegendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCdLegendaFocusLost(evt);
            }
        });

        tfdCdClassificacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdCdClassificacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCdClassificacaoFocusLost(evt);
            }
        });

        tfdCdCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdCdCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCdCategoriaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdCdClassificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(tfdCdLegenda)
                            .addComponent(tfdCdCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdIdioma)
                            .addComponent(tfdLegenda)
                            .addComponent(tfdClassificacao)
                            .addComponent(tfdCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfdCdIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfdDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(45, 45, 45)
                            .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdCdIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfdCdLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdCdClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdCdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblMensagem)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel1.setText("Buscar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Duração", "Valor", "Idioma", "Categoria"
            }
        ));
        tblFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilme);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Listagem", jPanel3);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmeMouseClicked

        String id = String.valueOf(tblFilme.getValueAt(tblFilme.getSelectedRow(), 0));
        String nome = String.valueOf(tblFilme.getValueAt(tblFilme.getSelectedRow(), 1));

        codigo = Integer.parseInt(id);
        Filme filme = new Filme();
        DaoFilme daoFilme = new DaoFilme();
        filme = daoFilme.consultaId(codigo);
        tfdNome.setText(nome);
        tfdDuracao.setText(String.valueOf(filme.getDuracao()));
        tfdValor.setText(String.valueOf(filme.getValor()));
        tfdCdIdioma.setText(String.valueOf(filme.getIdioma()));
        String dIdioma = daoIdioma.consultaId(filme.getIdioma()).getIdioma();
        tfdIdioma.setText(dIdioma);
        tfdCdLegenda.setText(String.valueOf(filme.getLegenda()));
        String dLegenda = daoLegenda.consultaId(filme.getLegenda()).getDescricao();
        tfdLegenda.setText(dLegenda);
        tfdCdClassificacao.setText(String.valueOf(filme.getClassificacao()));
        String dClassificacao = daoClassificacao.consultaId(filme.getClassificacao()).getDescricao();
        tfdClassificacao.setText(dClassificacao);
        tfdCdCategoria.setText(String.valueOf(filme.getCategoria()));
        String dCategoria = daoCategoria.consultaId(filme.getCategoria()).getDescricao();
        tfdCategoria.setText(dCategoria);
        jTabbedPane1.setSelectedIndex(0);
        tfdNome.requestFocus();
    }//GEN-LAST:event_tblFilmeMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String id = String.valueOf(tblFilme.getValueAt(tblFilme.getSelectedRow(), 0));
        DaoFilme dao = new DaoFilme();
        String mes = dao.exluir(dao.consultaId(Integer.parseInt(id)));
        JOptionPane.showMessageDialog(null, mes);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean result;
        try {
            Filme filme = new Filme();
            filme.setCodigo(codigo);
            filme.setNome(tfdNome.getText());
            filme.setDuracao(Integer.parseInt(tfdDuracao.getText()));
            filme.setCategoria(Integer.parseInt(tfdCdCategoria.getText()));
            filme.setClassificacao(Integer.parseInt(tfdCdClassificacao.getText()));
            filme.setIdioma(Integer.parseInt(tfdCdIdioma.getText()));
            filme.setLegenda(Integer.parseInt(tfdCdLegenda.getText()));
            filme.setValor(Double.parseDouble(tfdValor.getText()));
            result = DaoGenerico.getInstance().insert(filme);
            if (result) {
                JOptionPane.showMessageDialog(null, "Cadastro finalizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Cadastro com erro!");
            }
            inicia();
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private String validarCampos() {
        String mensagem = "";

        if (tfdNome.getText() == "") {
            tfdNome.setBackground(Color.YELLOW);
            tfdNome.requestFocus();
            mensagem = mensagem + "Campo NOME com problemas!\n";
        } else {
            tfdNome.setBackground(Color.WHITE);
        }
        if (tfdValor.getText() == "") {
            tfdValor.setBackground(Color.YELLOW);
            tfdValor.requestFocus();
            mensagem = mensagem + "Campo VALOR com problemas!\n";
        } else {
            tfdValor.setBackground(Color.WHITE);
        }
        if (tfdDuracao.getText() == "") {
            tfdDuracao.setBackground(Color.YELLOW);
            tfdDuracao.requestFocus();
            mensagem = mensagem + "Campo DURAÇÃO com problemas!\n";
        } else {
            tfdDuracao.setBackground(Color.WHITE);
        }
        lblMensagem.setText(mensagem);
        lblMensagem.setVisible(true);
        return mensagem;
    }
    private void tfdDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDuracaoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        List<Filme> resultado = new ArrayList();
        tblFilme.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblFilme.getColumnModel().getColumn(5).setPreferredWidth(50);
        DefaultTableModel modelo = (DefaultTableModel) tblFilme.getModel();
        modelo.setNumRows(0);
        try {
            DaoFilme daoFilme = new DaoFilme();
            resultado = daoFilme.consultaParam(tfdBuscar.getText());
            for (int i = 0; i < resultado.size(); i++) {
                Filme filme = resultado.get(i);
                modelo.addRow(new Object[]{filme.getCodigo(), filme.getNome(), filme.getDuracao(), filme.getValor(), filme.getIdioma(), filme.getCategoria()});

            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }

        // permite seleção de apenas uma linha da tabela
        tblFilme.setSelectionMode(0);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DlgConsulta consultar = new DlgConsulta(null, true);
        consultar.tabela = consulta;
        consultar.setVisible(true);
        if (consulta == "Idioma") {
            tfdCdIdioma.setText(String.valueOf(consultar.retorno));
            tfdCdIdioma.setEnabled(true);
            tfdCdIdioma.requestFocus();
        }
        if (consulta == "Legenda") {
            tfdCdLegenda.setText(String.valueOf(consultar.retorno));
            tfdCdLegenda.setEnabled(true);
            tfdCdLegenda.requestFocus();
        }
        if (consulta == "Categoria") {
            tfdCdLegenda.setText(String.valueOf(consultar.retorno));
            tfdCdLegenda.setEnabled(true);
            tfdCdLegenda.requestFocus();
        }
        if (consulta == "Classificacao") {
            tfdCdLegenda.setText(String.valueOf(consultar.retorno));
            tfdCdLegenda.setEnabled(true);
            tfdCdLegenda.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tfdCdIdiomaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdIdiomaFocusGained
        consulta = "Idioma";
    }//GEN-LAST:event_tfdCdIdiomaFocusGained

    private void tfdCdIdiomaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdIdiomaFocusLost
        Idioma idioma = daoIdioma.consultaId(Integer.parseInt(tfdCdIdioma.getText()));
        tfdIdioma.setText(idioma.getIdioma());
        tfdCdLegenda.requestFocus();
    }//GEN-LAST:event_tfdCdIdiomaFocusLost

    private void tfdCdLegendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdLegendaFocusGained
        consulta = "Legenda";
    }//GEN-LAST:event_tfdCdLegendaFocusGained

    private void tfdCdClassificacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdClassificacaoFocusGained
        consulta = "Classificacao";
    }//GEN-LAST:event_tfdCdClassificacaoFocusGained

    private void tfdCdCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdCategoriaFocusGained
        consulta = "Categoria";
    }//GEN-LAST:event_tfdCdCategoriaFocusGained

    private void tfdCdLegendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdLegendaFocusLost
        Legenda legenda = daoLegenda.consultaId(Integer.parseInt(tfdCdLegenda.getText()));
        tfdLegenda.setText(legenda.getDescricao());
        tfdCdClassificacao.requestFocus();
    }//GEN-LAST:event_tfdCdLegendaFocusLost

    private void tfdCdClassificacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdClassificacaoFocusLost
        Classificacao classificacao = daoClassificacao.consultaId(Integer.parseInt(tfdCdClassificacao.getText()));
        tfdClassificacao.setText(classificacao.getDescricao());
        tfdCdCategoria.requestFocus();
    }//GEN-LAST:event_tfdCdClassificacaoFocusLost

    private void tfdCdCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCdCategoriaFocusLost
        Categoria categoria = daoCategoria.consultaId(Integer.parseInt(tfdCdCategoria.getText()));
        tfdCategoria.setText(categoria.getDescricao());
        btnSalvar.requestFocus();
    }//GEN-LAST:event_tfdCdCategoriaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTable tblFilme;
    private javax.swing.JTextField tfdBuscar;
    private javax.swing.JTextField tfdCategoria;
    private javax.swing.JTextField tfdCdCategoria;
    private javax.swing.JTextField tfdCdClassificacao;
    private javax.swing.JTextField tfdCdIdioma;
    private javax.swing.JTextField tfdCdLegenda;
    private javax.swing.JTextField tfdClassificacao;
    private javax.swing.JTextField tfdDuracao;
    private javax.swing.JTextField tfdIdioma;
    private javax.swing.JTextField tfdLegenda;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdValor;
    // End of variables declaration//GEN-END:variables
}
